### PR TITLE
added el sewedy, procore, P&G, new jumia and vodafone internships

### PR DESCRIPTION
**Pull request by karimkohel**
it's inclusive of all fields but they do have a tech department and an IT department

### CODE REVIEW

**Comment by karimkohel** [comment]
now procore wants software interns without identifying clearly the position but the mentioned web stacks so that's that

**Comment by karimkohel** [comment]
it's because jumia added a front end intern position and included more details

**Comment by karimkohel** [comment]
forgot about P&G, it's in there too😪

**Comment by karimkohel** [comment]
there was a fake vodafone internship link going around, glad they cleared up this one on their main website

**Comment by karimkohel** [comment]
another P&G position and that's it for today

**Comment by MaiAhmedHussein** [comment]
> another P&G position and that's it for today

Thank youuu 😃

**Pull request merged**
