### PR TITLE
added Advansys, Klivvr and Dsquares internships

### PR DESCRIPTION
**Pull request by karimkohel**

### CODE REVIEW

**Comment by MaiAhmedHussein** [comment]
Are there any details about the internship fields?

**Comment by karimkohel** [comment]
the company states it's for computer science students but no further information provided

**Comment by moaz-eldefrawy** [comment]
Probably just change it to "no info" then.

**Comment by karimkohel** [comment]
So there is a standard at last, be it a simple one is still a win.

### For future reference 
if you value the impact of this repo then you would want the internships to be up on the repo as fast as possible, so in the future if you think any PR could be helpful to any one in the community and you think you can fix the problem with it easily, just do it instead of waiting for the author to get  back online. Any maintainer would be able to edit the code within a PR (edit permission for maintainers are given by default unless specifically revoked).
The author for any reason might not get to do it in time and the people missing out would be the community.

**Comment by moaz-eldefrawy** [comment]
Good job @karimkohel  <3.
We don't add people we don't know personally. However, if someone is contributing continuously like you, I think it makes sense to add them as a contributor.

**Pull request merged**
